### PR TITLE
feat: Adds Norwegian Helper

### LINKED ISSUE #25: Add a helper method for Norwegian Language
See #1 on how to implement it. It's very simple and it's the perfect candidate for the first issue collaboration.

Feel free to post any questions.

Code example: https://github.com/chgasparoto/aws-polly-voices/pull/2/files

### PR DESCRIPTION
**Pull request by NotKieran**
Inline with other helpers, adds norwegian language helper

fix #25

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/chgasparoto/aws-polly-voices/blob/master/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by NotKieran** [comment]
Have added to the helper list and the TODO list in the readme, and fixed the conflict with master. Should be good to go now!

**Comment by chgasparoto** [comment]
hey @NotKieran it seems your editor messed up with the formatting styling. Could you please commit only the changes related to your implementation?

**Comment by NotKieran** [comment]
Hey @chgasparoto I've made a bit of a mess of it and run out of time, will hopefully be able to get something working over the next few days. Sorry for the formatting issues!

**Comment by NotKieran** [comment]
Linted and tested successfully with the npm commands, should be okay. Merged the upstream into the branch too to resolve the conflicts myself. Should be all okay now.

**Comment by chgasparoto** [comment]
@NotKieran I just merged others PR into master right now. Could you please fix the conflict :)?

**Comment by NotKieran** [comment]
Looks far better to me this time, learning a lot in this process. Thanks for the patience!

**Comment by NotKieran** [comment]
@chgasparoto Should be good to go now!

**Pull request merged**
