### PR TITLE
feat: implement russian helper method

### PR DESCRIPTION
**Pull request by daltlc**
This pull closes issue #4

### CODE REVIEW

**Comment by chgasparoto** [comment]
Also, could you please add to this PR description something like closes #10 or fixes #10 to close the related issue?

**Comment by daltlc** [comment]
> Hi @daltlc
> 
> Could you please commit running `npm run commit` or amend you commit message to something like this "**feat: implement russian helper method**" in order to trigger a new version of this package in npm?
> 
> E.g.: https://github.com/chgasparoto/aws-polly-voices/pull/2/commits
> 
> Thank you.

I have change the commit message, and added description, telling which issue this pull will fix. 

Thanks

**Comment by chgasparoto** [comment]
Hi @daltlc thanks for changing the commit message! Could you please fix the conflict with the src/index.js file?

**Comment by daltlc** [comment]
> Hi @daltlc thanks for changing the commit message! Could you please fix the conflict with the src/index.js file?

I'm confused, I don't see a conflict.

**Pull request merged**
