### PR TITLE
Helper function for Korean language 

### PR DESCRIPTION
**Pull request by staphPLIS**
Fix https://github.com/chgasparoto/aws-polly-voices/issues/43

## Proposed changes

Adds Korean helper method

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/chgasparoto/aws-polly-voices/blob/master/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by SebastianStj** [comment]
Yeah sure, will fix it later today 👌

**Comment by SebastianStj** [comment]
@chgasparoto I think that all issues are fixed. Linters may fail - there is problem with recently merged https://github.com/chgasparoto/aws-polly-voices/pull/26 , I didn't fixed them since I saw that there are other open pull requests that are fixing this issues and I wanted to avoid conflicts with those changes

**Comment by chgasparoto** [comment]
@SebastianStj it seems ok to me

**Comment by chgasparoto** [comment]
@SebastianStj I just merged other PR into master. Could you please fix the conflict?

**Comment by chgasparoto** [comment]
I'll wait one more week for the conflict fix otherwise I'm going to close it 😉

**Pull request closed without merging**
